# Generated by Django 6.0.4 on 2026-05-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depatmet',
            new_name='Departmet',
        ),
        migrations.AddField(
            model_name='student',
            name='departmrct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_app.departmet'),
            preserve_default=False,
        ),
    ]
