# Generated by Django 6.0.4 on 2026-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0002_rename_depatmet_departmet_student_departmrct'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
