# Generated by Django 6.0.4 on 2026-05-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0003_student_email_student_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmet',
            old_name='name',
            new_name='dep_name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='sec_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='stu_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='stu_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
    ]
